travis:
  secure:
    BINSTAR_TOKEN: Sw8IlQTXI8K80OImN3YabwuBwV6DmtNzBfYk4WlF6wPFcEiEAF2JHLZBlqd8RI6PRCr6cCRWIpj+7/q/rEQi7YhF3fYyt/QFdQRqQQhCOHArYdCCnMdGU7MHO4MzEV3Ie8hQ3MZv36MP22CnXyRCk4i1h9DPZ11NRyokLfVRIYHxMYdqG+SBQ9MyWn722p4ikXc8HAGVCtBCRHShjxTg/nps5hjDrdO9mdG2j5dunhzsnsAtlROsQ1oTv7ssRJSSx9LwiTSq5onCWIuVTD6+LyBSdMItXMwQS0zIfFBzHdF4HBSYiRc6mCfbOOYkIFLtI1lBLAYdXCkw+t+5CIfSXl+2etSwsVVUNvwPh/t+yRTdoGGJzQ7qapNZlhv0U2i7kMc6u5ZUurzNZ+E3sLsxxqXCC/ypAwY4MijgSB4vO6B5WOyT9nvyjtKmiKiiG1UxgcmGahzby/6YxrXsZC8W37rBCNtLTssLQCNzyGpzCztFOSk3jysFVmo10/GaF+CPDpHbePZ3iclvPLvyg1m2kr1QwVSu4j3oCaSkfPqtr1w0z6LNAz/Nfgkjs7BuPBKMNfV2jXa5hUB4iNOxP77mXq2iDCsQcE2LrMlp5JV125BmrSOIILDzTYFh4l9c3osW64YY/3o5jYJHarCBsgB2Dw8USf9n93djdcjLhafkOqY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
